fix filterByWorkflow
apostrophecms/apostrophe-pieces-export pull request #11
Opened 2021-05-26 08:26 UTC by ecb34

sorry, when I changed from excludeTypes to includeType I forgot to remove the negation operator

2021-05-26 15:11 UTC, abea commented
This is a follow-up to #9?

2021-05-26 15:12 UTC, ecb34 commented
yes, it is

2021-06-10 16:27 UTC, boutell approved these changes

2021-06-10 16:28 UTC, boutell requested changes
One small thing, please update the changelog. Thanks.

2021-06-11 12:21 UTC, boutell approved these changes

2021-06-11 12:21 UTC, merged